# These are the funding platforms GitHub supports natively
# Fill in your actual usernames/links when ready

github: [JohanAludden]      # GitHub Sponsors (replace with your handle if enabled)
patreon: consideredweb      # Patreon username
open_collective:            # e.g. consideredweb
ko_fi:                      # e.g. consideredweb
custom:
  - https://consideredweb.com/support   # Any custom support/donation page